seeds: [42]
datasets:
  - rossmann
  - covid_deaths
  - m3_quarterly
  - hospital
  - solar
  - tourism_quarterly
  - m4_hourly
  - m3_other
  - tourism_monthly
  - m4_weekly
  - m3_monthly
  - nn5
  - electricity
  - kdd_2018

models:
  autogluon: 
    - key: presets
      values: [medium_quality]
    - key: run_time
      values: [30]
    - key: eval_metric
      values: [mean_wQuantileLoss] # AVAILABLE_METRICS = ["MASE", "MAPE", "sMAPE", "mean_wQuantileLoss", "MSE", "RMSE"]
      
